CREATE TABLE CIUDAD (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CODIGO CHAR(2),
    NOMBRE VARCHAR(20) NOT NULL,
    CONSTRAINT ID_CIUDAD_PK PRIMARY KEY (ID)
);

CREATE TABLE ARTISTA (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDOS VARCHAR(40) NOT NULL,
    TELEFONO VARCHAR(15),
    EMAIL VARCHAR(30),
    CIUDAD INTEGER,
    FECHA_NACIMIENTO DATE,
    SALARIO DECIMAL(7,2),
    FOTO VARCHAR(30),
    CONSTRAINT ID_ARTISTA_PK PRIMARY KEY (ID),
    CONSTRAINT CIUDAD_ARTISTA_FK FOREIGN KEY (CIUDAD) REFERENCES CIUDAD (ID)
);